### ISSUE TITLE
이 deno 프로젝트에 대해서

### ISSUE THREAD

**Issue by jeonghyeon-net** [Hot-key/Deno_Buffer#1]
귀하의 Deno_Buffer 라는 프로젝트를 보고 감명 받았습니다.

이 프로젝트에서 지원하는 Buffer 함수들에 대한 설명이나,
사용방법을 README.md 파일 등에 자세히 기록해주실 생각 없으신가요?

도움이 필요하다면 도와드리겠습니다.

**Comment by Hot-key** [comment]
일차적으로 버퍼의 기능이 완성되면 JSDoc을 이용하여 함수 설명을 한글로 기록할 예정입니다.

이후 버퍼 성능 테스트 및 최적화, 안정성 검증과정을 거친 후 영문으로 변역하여 JSDoc내용을 업데이트 할 생각입니다.

감사합니다.
